# Generated by Django 5.1.6 on 2025-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_category_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Dona'), ('ltr', 'Litr'), ('portion', 'Porsiya'), ('block', 'Block')], default='pcs', max_length=10),
        ),
    ]
