# Generated by Django 5.1.6 on 2025-02-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Dona'), ('ltr', 'Litr'), ('block', 'Block')], default='pcs', max_length=10),
        ),
    ]
