# Generated by Django 5.1.6 on 2025-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_usermessage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Dona'), ('ltr', 'Litr'), ('block', 'Block')], default='pcs', max_length=10, verbose_name='Tovar birligi'),
        ),
    ]
