# Generated by Django 5.1.6 on 2025-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Dona'), ('ltr', 'Litr'), ('kg', 'Kilogram'), ('block', 'Block')], default='pcs', max_length=10, verbose_name='Tovar birligi'),
        ),
    ]
