# Generated by Django 5.1.6 on 2025-02-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='reff',
            field=models.PositiveIntegerField(default=0, verbose_name='User Referral Count'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miqdori')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
    ]
