# Generated by Django 5.1.6 on 2025-02-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_product_quantity_alter_telegramuser_reff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('dona', 'Dona'), ('litr', 'Litr'), ('kg', 'Kilogram'), ('block', 'Block')], default='pcs', max_length=10, verbose_name='Tovar birligi'),
        ),
    ]
