# Generated by Django 5.1.6 on 2025-02-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('dona', 'Dona'), ('litr', 'Litr'), ('kg', 'Kilogram'), ('m', 'Metr'), ('block', 'Block')], default='pcs', max_length=10, verbose_name='Tovar birligi'),
        ),
    ]
